version: '3.8'
services:
  sast-integrator-svc:
    image: 10.8.60.32:5000/i3gis-registry/sast-integrator-service:latest
    container_name: sast-integrator-service
    restart: always
    env_file:
      - /var/lib/jenkins/deployment/.env
    ports:
      - '9095:9095'
    environment:
        APP_ENV: "development"
        DB_HOST: 10.8.60.33
        DB_USER: postgres
        DB_PASSWORD: "Redhat12345%21%40%23%24%25"
        DB_PORT: 5091
        DB_NAME: "sast_integrator"
        APP_PORT: "9095"
        ASOC_SERVICE_URL: "http://asoc-service:8080"
        SUPER_TOKEN: "eyJraWQiOiJwcml2YXRlX2tleSIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJ1c2VyX3Blcm1pc3Npb25zIjpbIjMwNyIsIjMwMyIsIjMxMCIsIjMwNSIsIjQwMSIsIjEwMSIsIjQwMyIsIjIwMiIsIjMwNiIsIjMwOCIsIjMwMiIsIjMwMSIsIjMxMSIsIjEwMiIsIjIwMyIsIjMwNCIsIjMwOSIsIjIwMSIsIjQwMiIsIjUwMSIsIjUwMiIsIjUwMyIsIjUwNCIsIjYwMSIsIjYwMiIsIjYwMyIsIjYwNCJdLCJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJBZG1pbmlzdHJhdG9yIGFkbWluIiwiaXNzIjoiaWQuY28uaTMuZ2VuZXJhbHNlcnZpY2UiLCJ1c2VyX2xvZ2luIjoiYWRtaW4iLCJ1c2VyX3JvbGVzIjpbInN1cGVyYWRtaW4iXSwiaWF0IjoxNjYzMTUxMDgwfQ.ULf7jLUsY3OoODXDRDM3oYc7nW_trBSrmb3cP0Tbk0cpVn8r-VoKlY1wHeB6zE1rqrTaNNFqwkgtEhMQKLA76Yd-MOAvfNDOiDCZCR6brhLdwzlTaJKxpyTEtOL6yzlwOPGJIcN0p69EcNo11phrL6Z-nlRTajtReOBGo8t9_hZcZmvwg3ugmsgOVSxG4N3_Jf4ojxjEwz6TpyWZnaS1R33q5QCnCEfG5QCn9bBi-T-QrE-n_n1R704fAc-7Ho9hkbWJXHJ9uF6NdMW9H08YOyv5vCcWOShjy-ZUgG0csSjvRPZYJQo-OTSKxCA4xyqd0nX2Xy8m3f_nJnX7WR1m9Q"
    networks:
        - i3gis-net
networks:
  i3gis-net:
    external: true
